# Generated by Django 5.1.2 on 2024-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_image', models.ImageField(upload_to='media/')),
                ('m_name', models.CharField(max_length=100)),
                ('m_role', models.CharField(max_length=100)),
                ('m_description', models.TextField()),
                ('m_insta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
