# Generated by Django 5.1.2 on 2024-11-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='p_user',
            new_name='user',
        ),
    ]
