# Generated by Django 5.1.2 on 2024-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postlike_post_alter_videolike_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_image',
            field=models.ImageField(blank=True, default='images/profile.jpg', null=True, upload_to='media/'),
        ),
    ]
