# Generated by Django 5.1.2 on 2024-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
